ALTER TYPE T_OSOBA ADD MAP MEMBER FUNCTION UTRIED RETURN VARCHAR2 CASCADE;
/

CREATE OR REPLACE TYPE BODY T_OSOBA AS
    
    MAP MEMBER FUNCTION UTRIED RETURN VARCHAR2 IS
    CELE_MENO VARCHAR2(30);
    BEGIN
        CELE_MENO := SELF.MENO || SELF.PRIEZVISKO;
        RETURN CELE_MENO;
    END UTRIED;

    MEMBER PROCEDURE VYPIS_ADRESU IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(SELF.MENO || ' ' || SELF.PRIEZVISKO);
        SELF.ADRESA.VYPIS;
    END VYPIS_ADRESU;
    
END;
/

CREATE TABLE ZAMESTNANCI 
(   OSOBA T_OSOBA,
    OS_CISLO INTEGER    );
    
INSERT INTO ZAMESTNANCI VALUES (T_OSOBA('Juraj', 'Pokorný', '901212/2453', T_ADRESA('Lipová 7', '08654', 'Hlohovec')), 556677);
INSERT INTO ZAMESTNANCI VALUES (T_OSOBA('Milan', 'Vlažný', '760421/3757', T_ADRESA('Korenená 58', '87548', 'Michalovce')), 556688);
INSERT INTO ZAMESTNANCI VALUES (T_OSOBA('Alžbeta', 'Slobodná', '765312/4583', T_ADRESA('Na hrane 5677', '24553', 'Bratislava')), 556699);

SELECT Z.OSOBA.MENO, Z.OSOBA.PRIEZVISKO 
FROM ZAMESTNANCI Z
ORDER BY Z.OSOBA.PRIEZVISKO;

SELECT Z.OSOBA.MENO, Z.OSOBA.PRIEZVISKO 
FROM ZAMESTNANCI Z
ORDER BY OSOBA;

ALTER TYPE T_OSOBA DROP MAP MEMBER FUNCTION UTRIED RETURN VARCHAR2 CASCADE;
/

ALTER TYPE T_OSOBA ADD ORDER MEMBER FUNCTION UTRIED(O T_OSOBA) RETURN INTEGER CASCADE;
/

CREATE OR REPLACE TYPE BODY T_OSOBA AS
    
    ORDER MEMBER FUNCTION UTRIED(O T_OSOBA) RETURN INTEGER IS
    BEGIN
        IF MENO < O.MENO THEN 
            RETURN -1;
        ELSIF MENO > O.MENO THEN 
            RETURN 1;
        ELSE 
            RETURN 0;
        END IF;
    END UTRIED;

    MEMBER PROCEDURE VYPIS_ADRESU IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(SELF.MENO || ' ' || SELF.PRIEZVISKO);
        SELF.ADRESA.VYPIS;
    END VYPIS_ADRESU;
    
END;
/

SELECT Z.OSOBA.MENO, Z.OSOBA.PRIEZVISKO 
FROM ZAMESTNANCI Z
ORDER BY Z.OSOBA.PRIEZVISKO;

SELECT Z.OSOBA.MENO, Z.OSOBA.PRIEZVISKO 
FROM ZAMESTNANCI Z
ORDER BY OSOBA;

CREATE OR REPLACE TYPE T_OSOBA AS OBJECT (
    MENO        VARCHAR(20),
    PRIEZVISKO  VARCHAR(30),
    ROD_CISLO   CHAR(11),
    ADRESA      T_ADRESA,
    
    MEMBER PROCEDURE VYPIS_ADRESU,
    ORDER MEMBER FUNCTION UTRIED(O T_OSOBA) RETURN INTEGER
) NOT FINAL;
/

CREATE TYPE T_STUDENT UNDER T_OSOBA (
    OS_CISLO    INTEGER,
    ROCNIK      CHAR(1)
);
