BEGIN
    FOR I IN (SELECT TABLE_NAME FROM TABS)
    LOOP
        EXECUTE IMMEDIATE('GRANT SELECT ON '||I.TABLE_NAME||' TO PUBLIC');
    END LOOP;
END;
/

SET SERVEROUTPUT ON;

BEGIN
    FOR I IN (SELECT TRIGGER_NAME FROM USER_TRIGGERS)
    LOOP
        EXECUTE IMMEDIATE('ALTER TRIGGER '||I.TRIGGER_NAME||' DISABLE');
    END LOOP;
END;
/

BEGIN
    FOR I IN (SELECT OBJECT_NAME, OBJECT_TYPE FROM USER_PROCEDURES WHERE OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION'))
    LOOP
        DBMS_OUTPUT.PUT_LINE('ALTER '|| I.OBJECT_TYPE ||' '|| I.OBJECT_NAME ||' COMPILE');
    END LOOP;
END;
/

BEGIN
    FOR I IN (SELECT * FROM P_OSOBA)
    LOOP
        DBMS_OUTPUT.PUT_LINE(I.MENO||' '||I.PRIEZVISKO);
    END LOOP;
END;
/

DECLARE
    CURSOR ZTP(OSOBA P_OSOBA.ROD_CISLO%TYPE) IS (SELECT ID_ZTP FROM P_ZTP);
    POM P_ZTP.ID_ZTP%TYPE;
BEGIN
    FOR I IN (SELECT * FROM P_OSOBA)
    LOOP
        DBMS_OUTPUT.PUT_LINE(I.MENO||' '||I.PRIEZVISKO);
        OPEN ZTP(I.ROD_CISLO);
        LOOP
            FETCH ZTP INTO POM;
            EXIT WHEN ZTP%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(POM);
        END LOOP;
        CLOSE ZTP;
    END LOOP;
END;
/
    