/* pre kazdy typ prispevku vypisat sumy za kazdy trimester(???) v minulom roku
(napr. pre obdobie 01-04); */

SELECT ID_TYPU, 
    SUM(CASE WHEN EXTRACT(MONTH FROM KEDY) BETWEEN 1 AND 4 THEN SUMA END) AS PRVY_TRIMESTER,
    SUM(CASE WHEN EXTRACT(MONTH FROM KEDY) BETWEEN 5 AND 8 THEN SUMA END) AS DRUHY_TRIMESTER,
    SUM(CASE WHEN EXTRACT(MONTH FROM KEDY) BETWEEN 9 AND 12 THEN SUMA END) AS TRETI_TRIMESTER
FROM P_PRISPEVKY
WHERE EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM KEDY) = 1
GROUP BY ID_TYPU;

-- select: vypisat tych zamestnavatelov, ktori zamestnali a do mesiaca vyhodili 
-- aspon jedneho zamestnanca;

SELECT NAZOV
FROM P_ZAMESTNANEC ZM JOIN P_ZAMESTNAVATEL ZA ON (ZM.ID_ZAMESTNAVATELA = ZA.ICO)
WHERE MONTHS_BETWEEN (DAT_DO, DAT_OD) <= 12;

-- select: vypisat zamestnavatelov, ktori aktualne zamestnava minimalne rok 
-- zamestnanca a ani raz mu nezaplatil poistenie;

SELECT NAZOV
FROM P_ZAMESTNANEC ZM 
    JOIN P_ZAMESTNAVATEL ZA ON (ZM.ID_ZAMESTNAVATELA = ZA.ICO)
WHERE DAT_DO IS NULL
    AND MONTHS_BETWEEN (SYSDATE, DAT_OD) >= 12
    AND ID_POISTENCA NOT IN (SELECT PL.ID_POISTENCA FROM P_ODVOD_PLATBA PL);
    
-- Štatistika poèet zamestnancov pod¾a veku v jednotlivých firmách

SELECT 
    NAZOV,
    FLOOR(MONTHS_BETWEEN(TO_DATE(SUBSTR(ROD_CISLO,1,2) || DECODE(SUBSTR(ROD_CISLO,3,1),'5','0','6','1',SUBSTR(ROD_CISLO,3,1)) || SUBSTR(ROD_CISLO,4,3), 'YYMMDD'), SYSDATE) / 12) AS VEK,
    COUNT(FLOOR(MONTHS_BETWEEN(TO_DATE(SUBSTR(ROD_CISLO,1,2) || DECODE(SUBSTR(ROD_CISLO,3,1),'5','0','6','1',SUBSTR(ROD_CISLO,3,1)) || SUBSTR(ROD_CISLO,4,3), 'YYMMDD'), SYSDATE) / 12)) AS POCET
FROM P_OSOBA 
    JOIN P_ZAMESTNANEC USING (ROD_CISLO)
    JOIN P_ZAMESTNAVATEL ZM ON (ZM.ICO = ID_ZAMESTNAVATELA)
WHERE ROD_CISLO IN (SELECT ROD_CISLO FROM P_ZAMESTNANEC)
GROUP BY 
    NAZOV,
    FLOOR(MONTHS_BETWEEN(TO_DATE(SUBSTR(ROD_CISLO,1,2) || DECODE(SUBSTR(ROD_CISLO,3,1),'5','0','6','1',SUBSTR(ROD_CISLO,3,1)) || SUBSTR(ROD_CISLO,4,3), 'YYMMDD'), SYSDATE) / 12);

-- Napiste funkciu objektu t_osoba ktora vracia datum narodenia osoby.

CREATE OR REPLACE TYPE T_OSOBA_2 AS OBJECT (
    ROD_CISLO   CHAR(11),
    MENO        VARCHAR2(20),
    PRIEZVISKO  VARCHAR2(30),
    
    MEMBER FUNCTION GET_DAT_NARODENIA RETURN DATE
);
/

CREATE OR REPLACE TYPE BODY T_OSOBA_2 AS
    MEMBER FUNCTION GET_DAT_NARODENIA RETURN DATE IS
    DAT_NAR DATE;
    BEGIN
        SELECT TO_DATE(
            SUBSTR(SELF.ROD_CISLO,1,2) || 
            DECODE(SUBSTR(SELF.ROD_CISLO,3,1),'5','0','6','1',SUBSTR(SELF.ROD_CISLO,3,1)) || 
            SUBSTR(SELF.ROD_CISLO,4,3), 'YYMMDD'
            )INTO DAT_NAR 
        FROM DUAL;
        RETURN DAT_NAR;
    END GET_DAT_NARODENIA;
END;
/








